# -*- coding: utf-8 -*-

import base64
import json
import logging
from pathlib import Path
from typing import Any, Optional

import numpy as np

from RosettaX.utils.upload_limits import format_upload_size, get_max_upload_bytes
from RosettaX.workflow import plotting

logger = logging.getLogger(__name__)


def build_upload_prompt_text() -> str:
    """
    Build the default calibration upload prompt text.
    """
    return (
        "Upload one or more calibration.json files generated by RosettaX. "
        f"Maximum file size: {format_upload_size()}."
    )


def parse_uploaded_calibration(
    *,
    contents: Any,
    filename: Any,
) -> tuple[str, dict[str, Any]]:
    """
    Parse and validate one uploaded calibration JSON file.
    """
    resolved_filename = str(filename or "").strip()

    if not resolved_filename:
        raise ValueError("Uploaded calibration file name is missing.")

    if Path(resolved_filename).suffix.lower() != ".json":
        raise ValueError("Calibration upload must be a .json file.")

    if not isinstance(contents, str) or "," not in contents:
        raise ValueError("Uploaded calibration file has a malformed Dash contents payload.")

    _, encoded_payload = contents.split(",", 1)

    raw_bytes = base64.b64decode(
        encoded_payload,
        validate=True,
    )

    if len(raw_bytes) > get_max_upload_bytes():
        raise ValueError(
            "Calibration upload exceeds the maximum supported size of "
            f"{format_upload_size()}."
        )

    record = json.loads(
        raw_bytes.decode("utf-8"),
    )

    if not isinstance(record, dict):
        raise ValueError("Calibration file root record is invalid.")

    schema = str(record.get("schema", "")).strip()

    if schema != "rosettax_calibration_v1":
        raise ValueError(
            f"Calibration file schema is unsupported: {schema or '<missing>'}."
        )

    payload = record.get("payload")

    if not isinstance(payload, dict):
        raise ValueError('Calibration file is missing top level "payload".')

    return resolved_filename, payload


def build_calibration_summary(
    *,
    selected_calibration: str,
    calibration_payload: dict[str, Any],
    calibration_file_path: Optional[Path] = None,
) -> dict[str, Any]:
    """
    Build a lightweight calibration summary for UI decisions.
    """
    calibration_type = str(
        calibration_payload.get(
            "calibration_type",
            "",
        )
    ).strip()

    source_channel = str(
        calibration_payload.get(
            "source_channel",
            "",
        )
    ).strip()

    output_quantity = str(
        calibration_payload.get(
            "output_quantity",
            "",
        )
    ).strip()

    version = calibration_payload.get(
        "version",
        None,
    )
    applied_output_channel_name = str(
        calibration_payload.get(
            "applied_output_channel_name",
            "",
        )
    ).strip()

    instrument_response = calibration_payload.get(
        "instrument_response",
        {},
    )

    if isinstance(instrument_response, dict):
        measured_channel = str(
            instrument_response.get(
                "measured_channel",
                "",
            )
        ).strip()

    else:
        measured_channel = ""

    if not source_channel and measured_channel:
        source_channel = measured_channel

    return {
        "selected_calibration": selected_calibration,
        "file_name": (
            calibration_file_path.name
            if calibration_file_path is not None
            else str(selected_calibration)
        ),
        "file_path": str(calibration_file_path) if calibration_file_path is not None else "",
        "calibration_type": calibration_type,
        "source_channel": source_channel,
        "output_quantity": output_quantity,
        "applied_output_channel_name": applied_output_channel_name,
        "version": version,
        "is_scattering": calibration_type == "scattering",
        "is_fluorescence": calibration_type == "fluorescence",
        "requires_target_model": calibration_type == "scattering",
        "is_valid": bool(calibration_type),
        "error": "",
        "calibration_payload": dict(calibration_payload),
    }


def normalize_calibration_summaries(
    calibration_summaries: Any,
) -> list[dict[str, Any]]:
    """
    Normalize a selected calibration summary payload into a list.
    """
    if isinstance(calibration_summaries, list):
        return [
            summary
            for summary in calibration_summaries
            if isinstance(summary, dict)
        ]

    if isinstance(calibration_summaries, dict):
        return [
            calibration_summaries,
        ]

    return []


def get_primary_calibration_summary(
    calibration_summaries: Any,
) -> Optional[dict[str, Any]]:
    """
    Return the first loaded calibration summary, if any.
    """
    normalized_summaries = normalize_calibration_summaries(
        calibration_summaries,
    )

    if not normalized_summaries:
        return None

    return normalized_summaries[0]


def get_primary_scattering_calibration_summary(
    calibration_summaries: Any,
) -> Optional[dict[str, Any]]:
    """
    Return the first scattering calibration summary that requires a target model.
    """
    for calibration_summary in normalize_calibration_summaries(
        calibration_summaries,
    ):
        if calibration_summary.get("requires_target_model"):
            return calibration_summary

    return None


def calibration_summaries_require_target_model(
    calibration_summaries: Any,
) -> bool:
    """
    Return whether any selected calibration requires scattering target parameters.
    """
    return (
        get_primary_scattering_calibration_summary(
            calibration_summaries,
        )
        is not None
    )


def resolve_target_mie_model(
    *,
    target_mie_model: Any,
) -> str:
    """
    Normalize the target Mie model value.
    """
    target_mie_model_string = str(
        target_mie_model or "Solid Sphere",
    ).strip()

    normalized_target_mie_model = target_mie_model_string.lower()

    if normalized_target_mie_model in {
        "core/shell sphere",
        "core shell sphere",
        "core-shell sphere",
        "coreshell sphere",
        "core_shell_sphere",
    }:
        return "Core/Shell Sphere"

    return "Solid Sphere"


def build_target_parameter_container_style(
    *,
    is_visible: bool,
    is_locked: bool = False,
) -> dict[str, str]:
    """
    Build the target parameter group visibility style.
    """
    return {
        "display": "block" if is_visible else "none",
        "opacity": "0.58" if is_locked else "1.0",
        "transition": "opacity 120ms ease-in-out",
    }


def build_scattering_target_model_container_style(
    *,
    is_visible: bool,
) -> dict[str, str]:
    """
    Build the target model container style.
    """
    return {
        "display": "block" if is_visible else "none",
        "overflow": "visible",
    }


def has_selected_target_model_preset(
    target_model_preset: Any,
) -> bool:
    """
    Return whether a concrete target model preset has been chosen.
    """
    return bool(str(target_model_preset or "").strip())


def normalize_axis_scale(
    value: Any,
    *,
    default: str,
) -> str:
    """
    Normalize an axis scale value.
    """
    value_string = str(value or "").strip().lower()

    if value_string in (
        "linear",
        "log",
    ):
        return value_string

    return default


def build_axis_scale_toggle_values(
    *,
    xscale: Any,
    yscale: Any,
) -> list[str]:
    """
    Convert x and y axis scales to Scatter2DGraph checklist values.
    """
    axis_scale_toggle_values: list[str] = []

    if str(xscale).strip().lower() == "log":
        axis_scale_toggle_values.append(
            plotting.scatter2d.Scatter2DGraph.x_log_value,
        )

    if str(yscale).strip().lower() == "log":
        axis_scale_toggle_values.append(
            plotting.scatter2d.Scatter2DGraph.y_log_value,
        )

    return axis_scale_toggle_values


def build_empty_target_mie_relation_figure() -> Any:
    """
    Build an empty target Mie relation preview figure.
    """
    return plotting.scatter2d.Scatter2DGraph.build_empty_figure(
        message="Select a scattering calibration to compute the preview.",
    )


def build_target_mie_relation_figure(
    *,
    full_diameter_values_nm: Any,
    full_coupling_values: Any,
    selected_diameter_values_nm: Any,
    selected_coupling_values: Any,
    approximation_diameter_values_nm: Any = None,
    approximation_coupling_values: Any = None,
    selected_interval: Any = None,
    show_selected_branch: bool,
    axis_scale_toggle_values: Any,
    x_axis_title: str,
) -> Any:
    """
    Build the target Mie relation preview figure.

    If the full relation is monotonic, the full curve is shown in blue.

    If the full relation is not monotonic, the selected valid monotonic branch
    is shown in blue, the rejected non-monotonic regions are shown in red, and
    the monotone approximation used for inversion is shown in green.
    """
    traces: list[plotting.scatter2d.Scatter2DTrace] = []

    if show_selected_branch and selected_interval is not None:
        full_diameter_array = np.asarray(
            full_diameter_values_nm,
            dtype=float,
        ).reshape(-1)

        full_coupling_array = np.asarray(
            full_coupling_values,
            dtype=float,
        ).reshape(-1)

        invalid_coupling_values = full_coupling_array.copy()
        invalid_coupling_values[
            selected_interval.start_index : selected_interval.end_index + 1
        ] = np.nan

        traces.append(
            plotting.scatter2d.Scatter2DTrace(
                x_values=selected_diameter_values_nm,
                y_values=selected_coupling_values,
                name="Valid monotonic branch",
                mode="lines",
                color="#1f77b4",
            )
        )

        if np.any(np.isfinite(invalid_coupling_values)):
            traces.append(
                plotting.scatter2d.Scatter2DTrace(
                    x_values=full_diameter_array,
                    y_values=invalid_coupling_values,
                    name="Invalid non-monotonic region",
                    mode="lines",
                    color="#d62728",
                )
            )

        if (
            approximation_diameter_values_nm is not None
            and approximation_coupling_values is not None
        ):
            approximation_diameter_array = np.asarray(
                approximation_diameter_values_nm,
                dtype=float,
            ).reshape(-1)
            approximation_coupling_array = np.asarray(
                approximation_coupling_values,
                dtype=float,
            ).reshape(-1)

            if approximation_diameter_array.size != approximation_coupling_array.size:
                raise ValueError(
                    "Approximation diameter and coupling arrays must have the same length."
                )

            if approximation_coupling_array.size == invalid_coupling_values.size:
                approximation_coupling_array = approximation_coupling_array.copy()
                approximation_coupling_array[
                    selected_interval.start_index : selected_interval.end_index + 1
                ] = np.nan

            traces.append(
                plotting.scatter2d.Scatter2DTrace(
                    x_values=approximation_diameter_array,
                    y_values=approximation_coupling_array,
                    name="Monotone approximation",
                    mode="lines",
                    color="#2ca02c",
                )
            )

    else:
        traces.append(
            plotting.scatter2d.Scatter2DTrace(
                x_values=full_diameter_values_nm,
                y_values=full_coupling_values,
                name="Valid monotonic relation",
                mode="lines",
                color="#1f77b4",
            )
        )

    figure = plotting.scatter2d.Scatter2DGraph.build_figure(
        traces=traces,
        title="Target Mie relation preview",
        x_axis_title=x_axis_title,
        y_axis_title="Theoretical optical coupling",
        axis_scale_toggle_values=axis_scale_toggle_values,
        show_grid=True,
        hovermode="closest",
        uirevision="target_mie_relation_preview",
    )

    figure.update_layout(
        legend={
            "x": 0.99,
            "y": 0.01,
            "xanchor": "right",
            "yanchor": "bottom",
            "bgcolor": "rgba(255, 255, 255, 0.72)",
            "bordercolor": "rgba(0, 0, 0, 0.18)",
            "borderwidth": 1,
        },
    )

    return figure


def build_preview_items(
    calibration_summary: dict[str, Any],
) -> list[Any]:
    """
    Build preview information items from calibration summary.

    Returns a list of HTML divs showing key calibration metadata.
    """
    import dash.html as html

    cal_type = str(calibration_summary.get("calibration_type", "")).strip().upper() or "n/a"
    source_ch = str(calibration_summary.get("source_channel", "")).strip() or "n/a"
    file_name = str(calibration_summary.get("file_name", "")).strip() or "n/a"
    output_name = str(calibration_summary.get("applied_output_channel_name", "")).strip() or "n/a"

    row = html.Div(
        [
            _build_preview_info_block(
                label="Calibration type",
                value=cal_type,
            ),
            _build_preview_info_block(
                label="Channel",
                value=source_ch,
            ),
            _build_preview_info_block(
                label="File",
                value=file_name,
                truncate=True,
            ),
            _build_preview_info_block(
                label="Output name",
                value=output_name,
                truncate=True,
            ),
        ],
        style={
            "display": "grid",
            "gridTemplateColumns": "minmax(130px, 0.9fr) minmax(110px, 0.8fr) minmax(200px, 1.5fr) minmax(180px, 1.1fr)",
            "gap": "8px",
            "width": "100%",
            "alignItems": "stretch",
        },
    )

    return [
        row,
    ]


def _build_preview_info_block(
    *,
    label: str,
    value: str,
    truncate: bool = False,
) -> Any:
    """
    Build a single preview info block.
    """
    import dash.html as html

    value_style = {
        "fontSize": "0.83rem",
        "fontWeight": "500",
        "lineHeight": "1.15",
        "color": "rgba(13, 25, 43, 0.9)",
        "whiteSpace": "nowrap" if truncate else "normal",
        "overflow": "hidden" if truncate else "visible",
        "textOverflow": "ellipsis" if truncate else "clip",
        "minWidth": "0",
        "flex": "1 1 auto",
    }

    return html.Div(
        [
            html.Span(
                f"{label}:",
                style={
                    "fontSize": "0.72rem",
                    "fontWeight": "600",
                    "opacity": 0.74,
                    "textTransform": "uppercase",
                    "letterSpacing": "0.4px",
                    "whiteSpace": "nowrap",
                },
            ),
            html.Span(
                value,
                style=value_style,
                title=value if truncate else None,
            ),
        ],
        style={
            "display": "flex",
            "alignItems": "center",
            "gap": "6px",
            "padding": "5px 8px",
            "background": "rgba(0, 123, 255, 0.035)",
            "borderRadius": "6px",
            "borderLeft": "2px solid rgba(0, 123, 255, 0.35)",
            "minHeight": "30px",
        },
    )
