name: Deploy to PyPi

on:
  push:
    tags: [ "v*" ]

permissions:
  contents: read

jobs:
  pure_package:
    uses: MartinPdeS/MPSActions/.github/workflows/publish_pure_package_to_PyPi.yml@v5
    with:
      python-version: "3.13"
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
